### ISSUE TITLE
Is dst capable of processing large datasets?

### ISSUE THREAD

**Issue by garyzhubc** [RAPLER/dst-1#4] opened 2022-11-06 05:56 UTC
Is dst capable of processing large datasets? Say 487409 rows and 2789 columns. Each row gives a bca focusing on a subset of the columns. Would the processing power of this program be enough?

**Comment by garyzhubc** [comment] 2022-11-06 06:06
What is the time complexity of `bca`?

**Comment by RAPLER** [comment] 2022-11-07 01:44
> Is dst capable of processing large datasets? Say 487409 rows and 2789 columns. Each row gives a bca focusing on a subset of the columns. Would the processing power of this program be enough?

Thanks for asking. The dst package has been designed to experiment with Dempster-Shafer theory on small sets. So far, it is not designed to work with a very large bca, if it is what you mean. However, it has been succesfully used by a researcher to aggregate two very large data sets  resulting from clustering algorithms applied to the same data. The two datasets had  a very large number of rows but four columns only. Dempster's rule of combination was applied row by row, so that there was no complexity issue. 

The combination of two bca is done by Dempster,s rule of combination. It has been proven that the time of computation by Dempster's rule  of combination is exponential (P. Orponen, “Dempster’s rule of combination is np-complete,” Artificial Intelligence, vol. 44, pp. 245–253, 1990.). See also the paper by Nic Wilson: Algorithms for Dempster-Shafer Theory, January 2000. 

Hope that helps,
Regards,
Claude

**Comment by garyzhubc** [comment] 2022-11-07 03:03
How can I show result for this? Here pcsk9_updown_bigsnp_obj$genotypes is the matrix above but I focus on one subset only so I suppose the computation wouldn't add up too much. However object bpa is too big for bcaPrint. Maybe I can start by finding the set with highest belief values? 

```
library(dst)

bpa <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[1,] <= 1), rep(1, M)), c(0.9,0.1))

for (i in 2:M) {
  print(i)
  if (ukb_data_ldl$ldl_highlow[i] == TRUE) {
    bpa_new <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[i,] >= 1), rep(1, M)), c(0.9,0.1))
    bpa <- dsrwon(bpa, bpa_new)
  } else {
    bpa_new <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[i,] <= 1), rep(1, M)), c(0.9,0.1))
    bpa <- dsrwon(bpa, bpa_new)
  }
}
bcaPrint(bpa)
```

**Comment by RAPLER** [comment] 2022-11-07 12:57
I would like to reproduce your problem, but I don't have the matrix
pcsk9_updown_bigsnp_obj in your message. Can you send some data to me
please? If there is a confidentiality issue, maybe some fictional data
would do.
Regards,
Claude

Le dim. 6 nov. 2022 à 22:03, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by RAPLER** [comment] 2022-11-20 03:13
Hi, 
Have you been able to solve your problem with package dst? If I can be of help, please ask.
Regards,
Claude

**Comment by RAPLER** [comment] 2022-11-20 03:15
Hi,
Have you been able to solve your problem with package dst? If I can be of
help, please ask.
Regards,
Claude

**Comment by RAPLER** [comment] 2022-11-20 14:29
Have you been able to solve your problem with dst papckage? Do you need
help?

Le dim. 6 nov. 2022 à 01:57, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2022-11-30 00:01
Here's another problem that I'm having. First I have used SNP ids for looping over the dataset

```
library(dst)

# initialize loop
bpa <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[1,] <= 1), rep(1, M)), c(0.9, 0.1), pcsk9_updown_bigsnp_obj$map$rsid)

# rowwise Dempster's rule of combination
N <- 10
for (i in 1:10) {
  print(i)
  if (ukb_data_ldl$ldl_highlow[i] == TRUE) {
    bpa_new <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[I, ] >= 1), rep(1, M)), c(0.9, 0.1), pcsk9_updown_bigsnp_obj$map$rsid)
    bpa <- dsrwon(bpa, bpa_new)
  } else if (ukb_data_ldl$ldl_highlow[i] == FALSE) {
    bpa_new <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[I, ] <= 1), rep(1, M)), c(0.9, 0.1), pcsk9_updown_bigsnp_obj$map$rsid)
    bpa <- dsrwon(bpa, bpa_new)
  }
}
```

![image](https://user-images.githubusercontent.com/30366447/204674573-d5efb576-b55d-44ec-ba3f-9f2617badbc4.png)

when I calculate belief and plausibility, all SNP ids turned into numbers

```
bel_bpa <- belplau(bpa)
```

![image](https://user-images.githubusercontent.com/30366447/204674637-5a1bfd37-50e4-4962-8e72-643736b296b9.png)

How can I keep the ids?

**Comment by garyzhubc** [comment] 2022-11-30 00:03
> I would like to reproduce your problem, but I don't have the matrix pcsk9_updown_bigsnp_obj in your message. Can you send some data to me please? If there is a confidentiality issue, maybe some fictional data would do. Regards, Claude Le dim. 6 nov. 2022 à 22:03, Peiyuan Zhu ***@***.***> a écrit :
> […](#)

Thanks. The data is confidential but it's quite big. It's a dataset of 487409 rows x 2789 columns with numerical values within [0,2]. I guess it can be generated.

**Comment by RAPLER** [comment] 2022-11-30 02:50
Hi,
Looking at your issue. I try to replicate your problem and get back to you
as soon as possible.

Thanks for asking.
Claude

Le mar. 29 nov. 2022 à 19:03, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2022-12-01 19:20
Thanks, do you think the issue about variable name can have a quick fix?

**Comment by RAPLER** [comment] 2022-12-01 21:25
I really don’t know. I will work on this tonight, namely on the code of the function ´belplau’.  In the initialization phase,  perhaps  you assign the column’s labels with the ´cname parameter?

C. B.

**Comment by RAPLER** [comment] 2022-12-02 00:43
OK, I see you have just done that. So yhe problem must come from
belplau function. I am looking at that.

**Comment by RAPLER** [comment] 2022-12-02 01:01
Hi,
In the code you produced, you loop over index "i" (small case), but you use
index I (uppercase I), which doesn't seem to be referenced anywhere else.
Is this a typing error?
----

print(i)

  if (ukb_data_ldl$ldl_highlow[i] == TRUE) {

    bpa_new <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[I, ]
>= 1), rep(1, M)), c(0.9, 0.1), pcsk9_updown_bigsnp_obj$map$rsid)

----


Claude

**Comment by RAPLER** [comment] 2022-12-02 02:55
So far, I have not been able to reproduce your issue. The structure of your resulting "bca" looks correct. When you call the "belplau" function, the label of each row should be of the following form:
label(1) + label(2) + ..., etc., where label(n) is the name that you assigned to the column "n" of your data.
Example:  suppose the data of a row of your result begins by: 
0 1 0 1 1 0 0 0 ...
According to your example, the label should begin by:
rs3753011 + rs77963205 + rs299873 + ...
Each label is separated by a "+" sign (this is done by function "nameRows" of my package).

The "belplau" function works in the following manner:
1. remove subsets with zero mass if asked;
2. does calculations of measures of belief and plausibility;
3. calls the function "nameRows" to establish the rownames of the result.

I don't understand where the labels of your "belplau" result come from. They look like a catenation of labels. Did you modify the "bca" resuly before calling "belplau" function?

Hopes that helps,

**Comment by garyzhubc** [comment] 2022-12-05 07:11
> Hi, In the code you produced, you loop over index "i" (small case), but you use index I (uppercase I), which doesn't seem to be referenced anywhere else. Is this a typing error? ---- print(i) if (ukb_data_ldl$ldl_highlow[i] == TRUE) { bpa_new <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[I, ]
> […](#)

Hi, that "I" must be caused by autocorrection when I'm pasting the code as a GitHub issue.

**Comment by RAPLER** [comment] 2022-12-05 15:16
As you have seen in the GitHub issue, I have explained how "belplau"
function creates the row labels of the result. To check the match of each
row label with the (0,1) vector of its row, you could use function
"tabresul". This function binds the data matrix "tt" with  the result of
function "belplau".
Claude

Le lun. 5 déc. 2022 à 02:11, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by RAPLER** [comment] 2022-12-06 21:36
From the code you produced, I understand that the SNP ids have been used to
assign column names to the matrix "tt"  that you created with the "bca"
function.
"bpa <- bca(rbind(as.integer(pcsk9_updown_bigsnp_obj$genotypes[1,] <= 1),
rep(1, M)), c(0.9, 0.1), pcsk9_updown_bigsnp_obj$map$rsid"
At the end of the loop, the bca you obtain has your SNP ids stored in the
valuenames parameter.

When you use the function "belplau", you don't see the SNP ids because the
are not shown, but they are there as column names of the matrix "tt" of the
"bca" result.
To see them in relation with the measure of belief and plausibility, you
must use function "tabresul".
Unlike function "belplau", function "tabresul" does not reconstruct the row
names. So you can assign simple rownames of your choice to the tt matrix of
your resulting bca before calling function "tabresul".
Please do tell me if this works for you.
Regards,
Claude

Le mar. 29 nov. 2022 à 19:01, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2022-12-14 22:46
Ok I was able to fix the index problem. I think it's a mistake that I put an extra indexing step that created the problem.

The more important problem is that the code doesn't seem to scale in such a big dataset. The loop stopped at i=12. I'm not sure exactly which function from the package that generated this error of infinite recursion. But maybe it's just too big. Also it doesn't seem to utilize GPU or multiple cores, for example, for a constant factor speedup. 

Working on such a dataset seem to occupy a lot of memory. I kept running into memory problem but not it seems to be okay since I requested to use 1kgb of memory. However, the new problem is this infinite recursion. 

```
[1] "genotype loaded"
[1] "phenotype loaded"
[1] "initialization"
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Execution halted
```

**Comment by garyzhubc** [comment] 2022-12-14 22:48
> > I would like to reproduce your problem, but I don't have the matrix pcsk9_updown_bigsnp_obj in your message. Can you send some data to me please? If there is a confidentiality issue, maybe some fictional data would do. Regards, Claude Le dim. 6 nov. 2022 à 22:03, Peiyuan Zhu _**@**_.***> a écrit :
> > […](#)
> 
> Thanks. The data is confidential but it's quite big. It's a dataset of 487409 rows x 2789 columns with numerical values within [0,2]. I guess it can be generated.

I'm not sure if you have ever experimented this package on large dataset like this, but it seems to take forever to run.

**Comment by garyzhubc** [comment] 2022-12-15 00:01
I'm okay with only using a few rows, but I need to include a large number of columns.

**Comment by garyzhubc** [comment] 2022-12-15 15:53
The system support person told me:

"This looks like an error in your code: you are probably calling a given function inside the same function.

A similar case that gives such error is discussed here:

https://stackoverflow.com/questions/49368446/error-evaluation-nested-too-deeply-infinite-recursion-optionsexpressions

You will have to rename your function if that's the case."

**Comment by RAPLER** [comment] 2022-12-16 02:58
A recursive function called  "doubles" is used by function "dsrwon".  I
have removed it from this function. You can go to my page on github to
installthe latest pre-release version of the package (dst v1.5.1.9001).

As I said earlier, the package has not been designed to work wiith big data.
It don't make use of a GPU or multiple cores. Belief functions are defined
of  the collection of all subsets of a set of possibilities. With a set of
2789 possibilities, you have a potential of exp(2789) subsets.

Since you want to combine more than 400 000  bca's together,  the size of
the resulting data matrix will become rapidly very large.The time of
computation of Dempster's rule of combination is exponential in the number
of focal elements.  Maybe a way to cope with that would be to make a
truncation of the resulting bca after a few steps, using a treshold value,
e.g. m less than a small value which would serve to do the union of the
subsets with small masses.

Regards,

Claude

Le jeu. 15 déc. 2022 à 10:53, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2022-12-16 18:47
Re computation on high dimensional datasets: I noticed Barnett has two papers that addresses the computation issue for simple support functions. It's said that it gives linear complexity.

Jeffrey A. Barnett, Computational methods for a mathematical theory of evidence,
Proceedings of the 7th National Conference on Artificial Intelligence (AAAI-88),
1981, pp. 868–875.

Jeffrey A. Barnett, Calculating Dempster–Shafer plausibility, IEEE Transactions on Pattern
Analysis and Machine Intelligence 13 (1991), no. 6, 599–602.

**Comment by RAPLER** [comment] 2022-12-17 02:42
Thanks for pointing out these two papers. However, it is not possible for
me to quickly realize an algorithm. I will still do some research on this
side.

Le ven. 16 déc. 2022 à 13:48, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2023-04-02 06:04
> A recursive function called "doubles" is used by function "dsrwon". I have removed it from this function. You can go to my page on github to installthe latest pre-release version of the package (dst v1.5.1.9001). As I said earlier, the package has not been designed to work wiith big data. It don't make use of a GPU or multiple cores. Belief functions are defined of the collection of all subsets of a set of possibilities. With a set of 2789 possibilities, you have a potential of exp(2789) subsets. Since you want to combine more than 400 000 bca's together, the size of the resulting data matrix will become rapidly very large.The time of computation of Dempster's rule of combination is exponential in the number of focal elements. Maybe a way to cope with that would be to make a truncation of the resulting bca after a few steps, using a treshold value, e.g. m less than a small value which would serve to do the union of the subsets with small masses. Regards, Claude Le jeu. 15 déc. 2022 à 10:53, Peiyuan Zhu ***@***.***> a écrit :
> […](#)

Is truncation a function that's realized in this package?

**Comment by RAPLER** [comment] 2023-04-02 19:41
Hi,

I have added a pre-release v1.5.1.9002 which contains function bcatrunc.
See on github (https://github.com/RAPLER/dst-1/releases/tag/v1.5.1.9002).

I haven't done any serious study of the effects of a truncation on the
final results. If only for presentation purposes, there should be no
problem. However, there will likely  be a bias in the results if used
repeatedly (in a loop of calculations).

I also added the ability to use multiple cores with Dempster's rule of
combination (function dsrwon). If you specify mcores = "yes" in the
function call, function will use all of your cores minus one to perform the
calculations. This should be useful if you have at least one bca with a
great number of rows.

Regards,

Claude

Le dim. 2 avr. 2023 à 02:04, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2023-04-02 19:51
I'll be interested in studying the effect of truncation methodologically. Would you be interested in connecting and have a chat? Also I'm interested to be involved in the development of this package. I'm currently using this for my work, and would welcome any collaboration.

**Comment by RAPLER** [comment] 2023-04-03 01:55
Yes, we could definitely chat and see how we can work together to improve
the dst package.
Do you have time in the evening, Monday or Tuesday? I can free up time
between 8:00 p.m. and 9:00 p.m. Montreal time. I'm not familiar with chat
processes. Can you tell me how you want to proceed?

Regards,
Claude

Le dim. 2 avr. 2023 à 15:51, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2023-04-03 01:58
Hi, maybe let me know your email so I can send you a zoom invite from
google calendar. Is this possible? Best, Gary

**Comment by RAPLER** [comment] 2023-04-03 13:44
Hi Gary,

You can reach me at this email address: ***@***.***
regards,
Claude

Le dim. 2 avr. 2023 à 21:58, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2023-04-03 15:54
Hi, it looks like your email is hidden by GitHub so it appears as " ***@***.*** ". Do you have a LinkedIn account? What's your full name? Otherwise maybe you could add your email to the README file?

**Comment by RAPLER** [comment] 2023-04-03 19:01
I am not on LinkedIn. But if you look for dst package on CRAN, you will
find my full name (Claude Boivin) and my  email address in the reference
manual (dst.pdf).


Le lun. 3 avr. 2023 à 11:54, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by RAPLER** [comment] 2023-05-20 02:04
A new version of function "dsrwon" (Dempster's rule of combination) has been uploaded to bca_mod branch  for testing. When constructing a "bca",  just put a list of subsets labels and the size of your frame of discernment, instead of describing your subsets by a (0,1) matrix,. These labels should serve to identify your variables (columns of your data). This is important for the intersections to work properly. See the example in the documentation of the function.
Good luck!

**Comment by RAPLER** [comment] 2023-05-23 01:51
I have made changes to the four following functions to allow computations using subsets names instead of a description matrix of the subsets (0,1)'s matrix:
bca: basic chance assignment
dsrwon: Dempster's rule of combination
nzdsr: normalization of results from dsrwon if empty set has non zero mass
belplau: computation of the measures of belief and plausibility.

These changes are done in the bca_mod branch

**Comment by garyzhubc** [comment] 2023-05-24 23:26
Thanks for the update. Now it is capable of running on Compute Canada cluster for at least a little while. That's great news. 

I'm having this question. If I only want to compute belplau of a few subsets is it possible to avoid the computing of the belplau for all nonzero focal elements? I think it'd be much faster to evaluate the results this way.

**Comment by garyzhubc** [comment] 2023-05-24 23:31
It looks like despite using relnb, tt and l12 still created as a big matrix so it's going to be quite memorable consuming. Could we use labels for this part as well?

**Comment by garyzhubc** [comment] 2023-05-24 23:31
![image](https://github.com/RAPLER/dst-1/assets/30366447/6f015d14-d983-4e2d-abb2-ceda1f1c4be4)

**Comment by garyzhubc** [comment] 2023-05-24 23:33
This is the result after combing 14 beliefs with 32 cpus and it's still combining the 15th belief after 3:15 hours.

**Comment by garyzhubc** [comment] 2023-05-24 23:39
The whole bpa object needs 157.3MB memory. I suppose this could be significantly reduced with a better storage of sparse matrices. I'm sure there are storage methods that can both allow efficient parallel computation but also need only small storage. Not sure if this would work but for instance: https://www.geeksforgeeks.org/working-with-sparse-matrices-in-r-programming/

**Comment by garyzhubc** [comment] 2023-05-24 23:46
Also more code comments would be appreciated for belplau.

**Comment by RAPLER** [comment] 2023-07-04 12:46
I am working on allowing sparse matrices in the code.

**Comment by garyzhubc** [comment] 2023-07-04 19:24
Thanks

**Comment by garyzhubc** [comment] 2023-07-04 19:26
The combination doesn't seem to work very well. I'm going to restrict the problem to a smaller subset of SNPs with a known variant and see how it works. That way I could shuffle the computation issue aside at least temporarily and look at the statistics.

**Comment by RAPLER** [comment] 2023-09-18 01:50
I have published a new pre-release for testing. This pre-release should allow:

the use of sparse matrices to do the combination of bca's by function dsrwon;
the use of subsets names to do the intersections (instead of (0,1) matrices);
the use of subsets names to identify the contributions to each subset resulting form the intersections;
the use of parallel processing.

I doubt there will be improvement of computing time, but use of sparse matrices should be of help for the data management matter.

**Comment by garyzhubc** [comment] 2023-09-19 16:36
Thanks! Could you also create a profiling tool so I can know how much computation is taken at each type of operations (intersection, multiplication, addition)?Sent from my iPhoneOn Sep 17, 2023, at 6:50 PM, Claude Boivin ***@***.***> wrote:﻿
I have published a new pre-release for testing. This pre-release should allow:
the use of sparse matrices to do the combination of bca's by function dsrwon;
the use of subsets names to do the intersections (instead of (0,1) matrices);
the use of subsets names to identify the contributions to each subset resulting form the intersections;
the use of parallel processing.
I doubt there will be improvement of computing time, but use of sparse matrices should be of help for the data management matter.

**Comment by RAPLER** [comment] 2023-09-23 00:50
Hi Gary,


I am using the profiler (from the profvis library) to obtain a breakdown of
the time and memory used by each line of code. As for counting operations,
I am still looking for a solution.


Best regards,

Claude

Le mar. 19 sept. 2023 à 12:36, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by garyzhubc** [comment] 2023-09-27 18:59
So it looks like the new version doesn't automatically do the conversion
into a computation with a sparse matrix if I use the code that I used
before.

The bca function has no change that has to do with the sparse matrix.
However, the dsrwon function has changes that have to do with the new
argument sparseM. I'm puzzled because I suppose I need to construct sparse
bcas' first?

Can you provide more details on how to use sparse matrices for computation?

**Comment by garyzhubc** [comment] 2023-09-27 19:09
<img width="683" alt="image" src="https://github.com/RAPLER/dst-1/assets/30366447/a1c44141-5e39-4296-b9e2-41d61e2a7f84">

**Comment by garyzhubc** [comment] 2023-09-27 19:10
Looks like it's already working with sparseMatrix.

**Comment by garyzhubc** [comment] 2023-09-28 00:55
Report a bug in the new version with sparse matrix. 

```
> nzdsr(bpa)
Error in nzdsr(bpa) : object 'm_empty' not found
```

**Comment by RAPLER** [comment] 2023-09-28 01:09
You only have to convert the tt matrix of the existing bca submitted, by
adding a line of code like this:
<my_bca$tt <- methods::as(my_bca$tt, "RsparseMatrix")>.

This way, your original tt matrix will be converted to a sparse matrix.
Maybe you will want to save the original tt matrix, in case something goes
wrong.

To submit sparse matrices to "dsrwon", you add the parameter sparseM =
TRUE. The tt matrix of the resulting bca will be sparse.

I will update the documentation of the "bca" function accordingly.

Also, I don't do an automatic conversion, because I have not tested sparse
matrices with product spaces (belief networks), only with the repeated use
of dsrwon on a single frame of discernment.

But it is a good idea to do the conversion on demand.

Le mer. 27 sept. 2023 à 15:10, Peiyuan Zhu ***@***.***> a
écrit :

**Comment by RAPLER** [comment] 2023-09-28 01:55
I have done a patch for the bug in the function nzdsr.

**Closed as completed** 2023-11-29 08:11 UTC
